# Generated by Django 3.0.2 on 2020-02-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeminjamanAlat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapeminjamanalat',
            name='no',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
