# Generated by Django 3.0.2 on 2020-02-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeminjamanAlat', '0002_datapeminjamanalat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapeminjamanalat',
            name='no',
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='angkatan',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='jumlah',
            field=models.PositiveIntegerField(),
        ),
    ]
