# Generated by Django 3.0.2 on 2020-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeminjamanAlat', '0003_auto_20200202_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='program_studi',
            field=models.CharField(max_length=30),
        ),
    ]
