# Generated by Django 3.0.2 on 2020-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeminjamanAlat', '0004_auto_20200202_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='alat',
            field=models.CharField(choices=[('', ''), ('LCD (Kuliah)', 'LCD (Kuliah)'), ('LCD (Non-Kuliah)', 'LCD (Non-Kuliah)'), ('Layar Proyektor', 'Layar Proyektor'), ('VGA Pendek', 'VGA Pendek'), ('VGA Panjang', 'VGA Panjang'), ('HT display + HEADSET', 'HT display + HEADSET'), ('HT non-display + HEADSET', 'HT non-display + HEADSET')], max_length=100),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='angkatan',
            field=models.PositiveIntegerField(choices=[('', ''), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='hari',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='jenis_kelamin',
            field=models.CharField(choices=[('', ''), ('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='lama_peminjaman',
            field=models.CharField(choices=[('', ''), ('1 hari', '1 hari'), ('2 hari', '2 hari'), ('3 hari', '3 hari'), ('4 hari', '4 hari')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='nim',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='program_studi',
            field=models.CharField(choices=[('', ''), ('S1 Matematika', 'S1 Matematika'), ('S1 Biologi', 'S1 Biologi'), ('S1 Fisika', 'S1 Fisika'), ('S1 Kimia', 'S1 Kimia'), ('S1 Farmasi', 'S1 Farmasi'), ('S1 Informatika', 'S1 Informatika'), ('S1 Ilmu Lingkungan', 'S1 Ilmu Lingkungan'), ('D3 Teknik Informatika', 'D3 Teknik Informatika'), ('D3 Farmasi', 'D3 Farmasi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='tanggal',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='tempat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapeminjamanalat',
            name='waktu',
            field=models.CharField(max_length=30),
        ),
    ]
