# Generated by Django 3.0.2 on 2020-01-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEndLabkom', '0002_auto_20200130_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postingan',
            new_name='Post',
        ),
    ]
