# Generated by Django 3.0.2 on 2020-01-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEndLabkom', '0003_auto_20200130_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
