# Generated by Django 3.0.2 on 2020-01-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEndLabkom', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
