# Generated by Django 3.0.2 on 2020-01-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEndLabkom', '0005_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
