# Generated by Django 3.0.2 on 2020-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPeminjamanStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.CharField(max_length=12)),
                ('jenis_kelamin', models.CharField(choices=[('', ''), ('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('program_studi', models.CharField(choices=[('', ''), ('S1 Matematika', 'S1 Matematika'), ('S1 Biologi', 'S1 Biologi'), ('S1 Fisika', 'S1 Fisika'), ('S1 Kimia', 'S1 Kimia'), ('S1 Farmasi', 'S1 Farmasi'), ('S1 Informatika', 'S1 Informatika'), ('S1 Ilmu Lingkungan', 'S1 Ilmu Lingkungan'), ('D3 Teknik Informatika', 'D3 Teknik Informatika'), ('D3 Farmasi', 'D3 Farmasi')], max_length=30)),
                ('angkatan', models.PositiveIntegerField(choices=[('', ''), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('hari', models.CharField(max_length=7)),
                ('tanggal', models.CharField(max_length=25)),
                ('tempat', models.CharField(max_length=100)),
                ('waktu', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
